pub const WINDOW_WIDTH: u32 = 1500;
pub const WINDOW_HEIGHT: u32 = 720;

pub const RENDER_BUFFER_WIDTH: u32 = 200;
pub const RENDER_BUFFER_HEIGHT: u32 = 200;
pub const RENDER_BUFFER_SIZE: usize = (RENDER_BUFFER_WIDTH * RENDER_BUFFER_HEIGHT * 4) as usize;
